name: Pull Request Labeler
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Hauptrepo: Label setzen mit Token
      - name: Label PR (main repo)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Fork: Nur dry-run, kein Token
      - name: Label PR (fork, dry-run)
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "PR from fork: skipping labeler (no secrets available)"