name: Release Info
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      [
        labeled,
        unlabeled,
        opened,
        edited,
        reopened,
        synchronize,
        ready_for_review,
      ]

jobs:
  generate-pr-description:
    name: Generate the description on the pull request
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository # Nur im Hauptrepo
    defaults:
      run:
        shell: bash

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: octue/generate-pull-request-description@b5257de511dfdd6e1de7adee90b62b6279ce40a0 # 1.0.0.beta-2
        id: pr-description
        with:
          pull_request_url: ${{ github.event.pull_request.url }}
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update pull request body
        uses: riskledger/update-pr-description@bb136dcb15789ce886dee9c8e04332c5cbf34832 # v2
        with:
          body: ${{ steps.pr-description.outputs.pull_request_description }}
          token: ${{ secrets.GITHUB_TOKEN }}
