name: Release Info
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      [
        labeled,
        unlabeled,
        opened,
        edited,
        reopened,
        synchronize,
        ready_for_review,
      ]

jobs:
  generate-pr-description:
    name: Generate the description on the pull request
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit
          allowed-endpoints: |
            github.com:443
            api.github.com:443
            pre-commit.ci:443
            results.pre-commit.ci:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate pull request description (fake)
        if: ${{ github.event.pull_request.url != '' }}
        id: pr-description
        run: |
          echo "PR from fork: skipping labeler (no secrets available)"
          echo "${{ github.event.pull_request.url }}" > pr_url.txt

      - name: Upload PR URL artifact
        if: ${{ github.event.pull_request.url != '' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pr-url
          path: pr_url.txt
